//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaryHeartDiseaseProject.Admin.SuperManage
{
    public partial class AddAdmin
    {
        protected global::System.Web.UI.WebControls.DropDownList SelectHosptial;
    }
}
