//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/MedicalCertificate.xsd", IsNullable = false)]
public partial class MedicalCertificate
{
    private System.DateTime treatDateField;

    private object canBeTrustField;

    private object descriptionField;

    private object simpleDiseaseField;

    private MedicalCertificateHistoryDisease historyDiseaseField;

    private object firstTimeBloodPressureField;

    private object firstTimeHeartRateField;

    private MedicalCertificateFirstCNT firstCNTField;

    private object cNTBackTimeField;

    private System.DateTime firstHeartImageDateTimeField;

    private System.DateTime firstBloodPressureTestingTimeField;

    private System.DateTime firstReportTimeField;

    private MedicalCertificatePreTreat preTreatField;

    private MedicalCertificateKillipLevels killipLevelsField;

    private MedicalCertificateDiseaseWithState diseaseWithStateField;

    private MedicalCertificateCPRTimes cPRTimesField;

    private MedicalCertificateTreatState treatStateField;

    private MedicalCertificatePCI pCIField;

    private MedicalCertificateTransUpHospital transUpHospitalField;

    private MedicalCertificateAdjuvantDrug adjuvantDrugField;

    private MedicalCertificateOneDayState oneDayStateField;

    private object introduceEmergencyCoronaryConfirmField;

    private object emergencyCoronaryDateField;

    private object agreeEmergencyCoronaryConfirmField;

    private MedicalCertificateThrombolyticReason thrombolyticReasonField;

    /// <remarks/>
    public System.DateTime TreatDate
    {
        get
        {
            return this.treatDateField;
        }
        set
        {
            this.treatDateField = value;
        }
    }

    /// <remarks/>
    public object CanBeTrust
    {
        get
        {
            return this.canBeTrustField;
        }
        set
        {
            this.canBeTrustField = value;
        }
    }

    /// <remarks/>
    public object Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public object SimpleDisease
    {
        get
        {
            return this.simpleDiseaseField;
        }
        set
        {
            this.simpleDiseaseField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDisease HistoryDisease
    {
        get
        {
            return this.historyDiseaseField;
        }
        set
        {
            this.historyDiseaseField = value;
        }
    }

    /// <remarks/>
    public object FirstTimeBloodPressure
    {
        get
        {
            return this.firstTimeBloodPressureField;
        }
        set
        {
            this.firstTimeBloodPressureField = value;
        }
    }

    /// <remarks/>
    public object FirstTimeHeartRate
    {
        get
        {
            return this.firstTimeHeartRateField;
        }
        set
        {
            this.firstTimeHeartRateField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateFirstCNT FirstCNT
    {
        get
        {
            return this.firstCNTField;
        }
        set
        {
            this.firstCNTField = value;
        }
    }

    /// <remarks/>
    public object CNTBackTime
    {
        get
        {
            return this.cNTBackTimeField;
        }
        set
        {
            this.cNTBackTimeField = value;
        }
    }

    /// <remarks/>
    public System.DateTime FirstHeartImageDateTime
    {
        get
        {
            return this.firstHeartImageDateTimeField;
        }
        set
        {
            this.firstHeartImageDateTimeField = value;
        }
    }

    /// <remarks/>
    public System.DateTime FirstBloodPressureTestingTime
    {
        get
        {
            return this.firstBloodPressureTestingTimeField;
        }
        set
        {
            this.firstBloodPressureTestingTimeField = value;
        }
    }

    /// <remarks/>
    public System.DateTime FirstReportTime
    {
        get
        {
            return this.firstReportTimeField;
        }
        set
        {
            this.firstReportTimeField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificatePreTreat PreTreat
    {
        get
        {
            return this.preTreatField;
        }
        set
        {
            this.preTreatField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateKillipLevels KillipLevels
    {
        get
        {
            return this.killipLevelsField;
        }
        set
        {
            this.killipLevelsField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateDiseaseWithState DiseaseWithState
    {
        get
        {
            return this.diseaseWithStateField;
        }
        set
        {
            this.diseaseWithStateField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateCPRTimes CPRTimes
    {
        get
        {
            return this.cPRTimesField;
        }
        set
        {
            this.cPRTimesField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateTreatState TreatState
    {
        get
        {
            return this.treatStateField;
        }
        set
        {
            this.treatStateField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificatePCI PCI
    {
        get
        {
            return this.pCIField;
        }
        set
        {
            this.pCIField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateTransUpHospital TransUpHospital
    {
        get
        {
            return this.transUpHospitalField;
        }
        set
        {
            this.transUpHospitalField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateAdjuvantDrug AdjuvantDrug
    {
        get
        {
            return this.adjuvantDrugField;
        }
        set
        {
            this.adjuvantDrugField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateOneDayState OneDayState
    {
        get
        {
            return this.oneDayStateField;
        }
        set
        {
            this.oneDayStateField = value;
        }
    }

    /// <remarks/>
    public object IntroduceEmergencyCoronaryConfirm
    {
        get
        {
            return this.introduceEmergencyCoronaryConfirmField;
        }
        set
        {
            this.introduceEmergencyCoronaryConfirmField = value;
        }
    }

    /// <remarks/>
    public object EmergencyCoronaryDate
    {
        get
        {
            return this.emergencyCoronaryDateField;
        }
        set
        {
            this.emergencyCoronaryDateField = value;
        }
    }

    /// <remarks/>
    public object AgreeEmergencyCoronaryConfirm
    {
        get
        {
            return this.agreeEmergencyCoronaryConfirmField;
        }
        set
        {
            this.agreeEmergencyCoronaryConfirmField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateThrombolyticReason ThrombolyticReason
    {
        get
        {
            return this.thrombolyticReasonField;
        }
        set
        {
            this.thrombolyticReasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDisease
{
    private MedicalCertificateHistoryDiseaseHypertension hypertensionField;

    private MedicalCertificateHistoryDiseaseGlycuresis glycuresisField;

    private MedicalCertificateHistoryDiseaseCerebralThrombosis cerebralThrombosisField;

    private MedicalCertificateHistoryDiseaseCerebralHemorrhage cerebralHemorrhageField;

    private MedicalCertificateHistoryDiseaseAnemiaorOtherDisease anemiaorOtherDiseaseField;

    private MedicalCertificateHistoryDiseaseOther otherField;

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseHypertension Hypertension
    {
        get
        {
            return this.hypertensionField;
        }
        set
        {
            this.hypertensionField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseGlycuresis Glycuresis
    {
        get
        {
            return this.glycuresisField;
        }
        set
        {
            this.glycuresisField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseCerebralThrombosis CerebralThrombosis
    {
        get
        {
            return this.cerebralThrombosisField;
        }
        set
        {
            this.cerebralThrombosisField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseCerebralHemorrhage CerebralHemorrhage
    {
        get
        {
            return this.cerebralHemorrhageField;
        }
        set
        {
            this.cerebralHemorrhageField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseAnemiaorOtherDisease AnemiaorOtherDisease
    {
        get
        {
            return this.anemiaorOtherDiseaseField;
        }
        set
        {
            this.anemiaorOtherDiseaseField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateHistoryDiseaseOther Other
    {
        get
        {
            return this.otherField;
        }
        set
        {
            this.otherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseHypertension
{
    private object sureField;

    private byte durationField;

    private object treatStateField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public byte Duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    public object TreatState
    {
        get
        {
            return this.treatStateField;
        }
        set
        {
            this.treatStateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseGlycuresis
{
    private object sureField;

    private byte durationField;

    private object treatStateField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public byte Duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    public object TreatState
    {
        get
        {
            return this.treatStateField;
        }
        set
        {
            this.treatStateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseCerebralThrombosis
{
    private object sureField;

    private byte durationField;

    private object treatStateField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public byte Duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    public object TreatState
    {
        get
        {
            return this.treatStateField;
        }
        set
        {
            this.treatStateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseCerebralHemorrhage
{
    private object sureField;

    private byte durationField;

    private object treatUntillNowField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public byte Duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    public object TreatUntillNow
    {
        get
        {
            return this.treatUntillNowField;
        }
        set
        {
            this.treatUntillNowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseAnemiaorOtherDisease
{
    private object sureField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateHistoryDiseaseOther
{
    private string descriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateFirstCNT
{
    private string regularCNTField;

    private string resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RegularCNT
    {
        get
        {
            return this.regularCNTField;
        }
        set
        {
            this.regularCNTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificatePreTreat
{
    private MedicalCertificatePreTreatAcuteST acuteSTField;

    private object unAcuteSTField;

    private object uAPField;

    private MedicalCertificatePreTreatOther otherField;

    /// <remarks/>
    public MedicalCertificatePreTreatAcuteST AcuteST
    {
        get
        {
            return this.acuteSTField;
        }
        set
        {
            this.acuteSTField = value;
        }
    }

    /// <remarks/>
    public object UnAcuteST
    {
        get
        {
            return this.unAcuteSTField;
        }
        set
        {
            this.unAcuteSTField = value;
        }
    }

    /// <remarks/>
    public object UAP
    {
        get
        {
            return this.uAPField;
        }
        set
        {
            this.uAPField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificatePreTreatOther Other
    {
        get
        {
            return this.otherField;
        }
        set
        {
            this.otherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificatePreTreatAcuteST
{
    private object anteroseptalField;

    private object antethecaField;

    private object extensiveField;

    private object interiorWallField;

    private object backWallField;

    private object rightVentricularField;

    /// <remarks/>
    public object Anteroseptal
    {
        get
        {
            return this.anteroseptalField;
        }
        set
        {
            this.anteroseptalField = value;
        }
    }

    /// <remarks/>
    public object Antetheca
    {
        get
        {
            return this.antethecaField;
        }
        set
        {
            this.antethecaField = value;
        }
    }

    /// <remarks/>
    public object Extensive
    {
        get
        {
            return this.extensiveField;
        }
        set
        {
            this.extensiveField = value;
        }
    }

    /// <remarks/>
    public object InteriorWall
    {
        get
        {
            return this.interiorWallField;
        }
        set
        {
            this.interiorWallField = value;
        }
    }

    /// <remarks/>
    public object BackWall
    {
        get
        {
            return this.backWallField;
        }
        set
        {
            this.backWallField = value;
        }
    }

    /// <remarks/>
    public object RightVentricular
    {
        get
        {
            return this.rightVentricularField;
        }
        set
        {
            this.rightVentricularField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificatePreTreatOther
{
    private object sureField;

    private object descriptionField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public object Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateKillipLevels
{
    private object killipIField;

    private object killipIIField;

    private object killipIIIField;

    private object killipIVField;

    /// <remarks/>
    public object KillipI
    {
        get
        {
            return this.killipIField;
        }
        set
        {
            this.killipIField = value;
        }
    }

    /// <remarks/>
    public object KillipII
    {
        get
        {
            return this.killipIIField;
        }
        set
        {
            this.killipIIField = value;
        }
    }

    /// <remarks/>
    public object KillipIII
    {
        get
        {
            return this.killipIIIField;
        }
        set
        {
            this.killipIIIField = value;
        }
    }

    /// <remarks/>
    public object KillipIV
    {
        get
        {
            return this.killipIVField;
        }
        set
        {
            this.killipIVField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateDiseaseWithState
{
    private object hypotensionField;

    private object shockField;

    private MedicalCertificateDiseaseWithStateKILLIP kILLIPField;

    private MedicalCertificateDiseaseWithStateArrhythmia arrhythmiaField;

    private object mitralProlopseField;

    private object perforationOfVentricularSeptumField;

    private object strokeField;

    private object gastrointestinalBleedingField;

    private MedicalCertificateDiseaseWithStateVentricularBlocking ventricularBlockingField;

    private object oGLBField;

    /// <remarks/>
    public object Hypotension
    {
        get
        {
            return this.hypotensionField;
        }
        set
        {
            this.hypotensionField = value;
        }
    }

    /// <remarks/>
    public object Shock
    {
        get
        {
            return this.shockField;
        }
        set
        {
            this.shockField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateDiseaseWithStateKILLIP KILLIP
    {
        get
        {
            return this.kILLIPField;
        }
        set
        {
            this.kILLIPField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateDiseaseWithStateArrhythmia Arrhythmia
    {
        get
        {
            return this.arrhythmiaField;
        }
        set
        {
            this.arrhythmiaField = value;
        }
    }

    /// <remarks/>
    public object MitralProlopse
    {
        get
        {
            return this.mitralProlopseField;
        }
        set
        {
            this.mitralProlopseField = value;
        }
    }

    /// <remarks/>
    public object PerforationOfVentricularSeptum
    {
        get
        {
            return this.perforationOfVentricularSeptumField;
        }
        set
        {
            this.perforationOfVentricularSeptumField = value;
        }
    }

    /// <remarks/>
    public object Stroke
    {
        get
        {
            return this.strokeField;
        }
        set
        {
            this.strokeField = value;
        }
    }

    /// <remarks/>
    public object GastrointestinalBleeding
    {
        get
        {
            return this.gastrointestinalBleedingField;
        }
        set
        {
            this.gastrointestinalBleedingField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateDiseaseWithStateVentricularBlocking VentricularBlocking
    {
        get
        {
            return this.ventricularBlockingField;
        }
        set
        {
            this.ventricularBlockingField = value;
        }
    }

    /// <remarks/>
    public object OGLB
    {
        get
        {
            return this.oGLBField;
        }
        set
        {
            this.oGLBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateDiseaseWithStateKILLIP
{
    private object sureField;

    private object descriptionField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public object Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateDiseaseWithStateArrhythmia
{
    private object aPBField;

    private object aTsField;

    private object aFSField;

    private object afField;

    private object vPBField;

    private object vtField;

    private object vfField;

    /// <remarks/>
    public object APB
    {
        get
        {
            return this.aPBField;
        }
        set
        {
            this.aPBField = value;
        }
    }

    /// <remarks/>
    public object ATs
    {
        get
        {
            return this.aTsField;
        }
        set
        {
            this.aTsField = value;
        }
    }

    /// <remarks/>
    public object AFS
    {
        get
        {
            return this.aFSField;
        }
        set
        {
            this.aFSField = value;
        }
    }

    /// <remarks/>
    public object AF
    {
        get
        {
            return this.afField;
        }
        set
        {
            this.afField = value;
        }
    }

    /// <remarks/>
    public object VPB
    {
        get
        {
            return this.vPBField;
        }
        set
        {
            this.vPBField = value;
        }
    }

    /// <remarks/>
    public object VT
    {
        get
        {
            return this.vtField;
        }
        set
        {
            this.vtField = value;
        }
    }

    /// <remarks/>
    public object VF
    {
        get
        {
            return this.vfField;
        }
        set
        {
            this.vfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateDiseaseWithStateVentricularBlocking
{
    private object aVBIField;

    private object aVBIIField;

    private object aVBIIIField;

    private object aFSField;

    private object rBBBField;

    private object aVBOtherField;

    /// <remarks/>
    public object AVBI
    {
        get
        {
            return this.aVBIField;
        }
        set
        {
            this.aVBIField = value;
        }
    }

    /// <remarks/>
    public object AVBII
    {
        get
        {
            return this.aVBIIField;
        }
        set
        {
            this.aVBIIField = value;
        }
    }

    /// <remarks/>
    public object AVBIII
    {
        get
        {
            return this.aVBIIIField;
        }
        set
        {
            this.aVBIIIField = value;
        }
    }

    /// <remarks/>
    public object AFS
    {
        get
        {
            return this.aFSField;
        }
        set
        {
            this.aFSField = value;
        }
    }

    /// <remarks/>
    public object RBBB
    {
        get
        {
            return this.rBBBField;
        }
        set
        {
            this.rBBBField = value;
        }
    }

    /// <remarks/>
    public object AVBOther
    {
        get
        {
            return this.aVBOtherField;
        }
        set
        {
            this.aVBOtherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateCPRTimes
{
    private object sureField;

    private object timesField;

    /// <remarks/>
    public object Sure
    {
        get
        {
            return this.sureField;
        }
        set
        {
            this.sureField = value;
        }
    }

    /// <remarks/>
    public object Times
    {
        get
        {
            return this.timesField;
        }
        set
        {
            this.timesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateTreatState
{
    private MedicalCertificateTreatStateIntravenousThrombolysis intravenousThrombolysisField;

    /// <remarks/>
    public MedicalCertificateTreatStateIntravenousThrombolysis IntravenousThrombolysis
    {
        get
        {
            return this.intravenousThrombolysisField;
        }
        set
        {
            this.intravenousThrombolysisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateTreatStateIntravenousThrombolysis
{
    private object urokinaseField;

    private object alteplaseField;

    private object reteplaseField;

    private MedicalCertificateTreatStateIntravenousThrombolysisComplication complicationField;

    private object passField;

    private object beforeTreatTimeField;

    /// <remarks/>
    public object Urokinase
    {
        get
        {
            return this.urokinaseField;
        }
        set
        {
            this.urokinaseField = value;
        }
    }

    /// <remarks/>
    public object Alteplase
    {
        get
        {
            return this.alteplaseField;
        }
        set
        {
            this.alteplaseField = value;
        }
    }

    /// <remarks/>
    public object Reteplase
    {
        get
        {
            return this.reteplaseField;
        }
        set
        {
            this.reteplaseField = value;
        }
    }

    /// <remarks/>
    public MedicalCertificateTreatStateIntravenousThrombolysisComplication Complication
    {
        get
        {
            return this.complicationField;
        }
        set
        {
            this.complicationField = value;
        }
    }

    /// <remarks/>
    public object Pass
    {
        get
        {
            return this.passField;
        }
        set
        {
            this.passField = value;
        }
    }

    /// <remarks/>
    public object BeforeTreatTime
    {
        get
        {
            return this.beforeTreatTimeField;
        }
        set
        {
            this.beforeTreatTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateTreatStateIntravenousThrombolysisComplication
{
    private object anaphylaxisField;

    private object bleedField;

    private object reperfusionArrhythmiaField;

    /// <remarks/>
    public object Anaphylaxis
    {
        get
        {
            return this.anaphylaxisField;
        }
        set
        {
            this.anaphylaxisField = value;
        }
    }

    /// <remarks/>
    public object Bleed
    {
        get
        {
            return this.bleedField;
        }
        set
        {
            this.bleedField = value;
        }
    }

    /// <remarks/>
    public object ReperfusionArrhythmia
    {
        get
        {
            return this.reperfusionArrhythmiaField;
        }
        set
        {
            this.reperfusionArrhythmiaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificatePCI
{
    private object d2BTimeField;

    private object isSucceedField;

    /// <remarks/>
    public object D2BTime
    {
        get
        {
            return this.d2BTimeField;
        }
        set
        {
            this.d2BTimeField = value;
        }
    }

    /// <remarks/>
    public object IsSucceed
    {
        get
        {
            return this.isSucceedField;
        }
        set
        {
            this.isSucceedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateTransUpHospital
{
    private object transUpHospitalConfirmField;

    private object transUpHospitalLeverField;

    private object transeferDateField;

    private object connectUpHospitalConfirmField;

    private object upHospitalLaboratoryField;

    /// <remarks/>
    public object TransUpHospitalConfirm
    {
        get
        {
            return this.transUpHospitalConfirmField;
        }
        set
        {
            this.transUpHospitalConfirmField = value;
        }
    }

    /// <remarks/>
    public object TransUpHospitalLever
    {
        get
        {
            return this.transUpHospitalLeverField;
        }
        set
        {
            this.transUpHospitalLeverField = value;
        }
    }

    /// <remarks/>
    public object TranseferDate
    {
        get
        {
            return this.transeferDateField;
        }
        set
        {
            this.transeferDateField = value;
        }
    }

    /// <remarks/>
    public object ConnectUpHospitalConfirm
    {
        get
        {
            return this.connectUpHospitalConfirmField;
        }
        set
        {
            this.connectUpHospitalConfirmField = value;
        }
    }

    /// <remarks/>
    public object UpHospitalLaboratory
    {
        get
        {
            return this.upHospitalLaboratoryField;
        }
        set
        {
            this.upHospitalLaboratoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateAdjuvantDrug
{
    private object aspirinDosageField;

    private object clopidogrelDosageField;

    private object loadStatinUsedField;

    private object loadStatinDosageField;

    /// <remarks/>
    public object AspirinDosage
    {
        get
        {
            return this.aspirinDosageField;
        }
        set
        {
            this.aspirinDosageField = value;
        }
    }

    /// <remarks/>
    public object ClopidogrelDosage
    {
        get
        {
            return this.clopidogrelDosageField;
        }
        set
        {
            this.clopidogrelDosageField = value;
        }
    }

    /// <remarks/>
    public object LoadStatinUsed
    {
        get
        {
            return this.loadStatinUsedField;
        }
        set
        {
            this.loadStatinUsedField = value;
        }
    }

    /// <remarks/>
    public object LoadStatinDosage
    {
        get
        {
            return this.loadStatinDosageField;
        }
        set
        {
            this.loadStatinDosageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateOneDayState
{
    private object treatResultField;

    private object deadTimeField;

    private object deadForVentriclarArrhythmiasField;

    private object deadForCardiacArrestField;

    private object deadForCardiogenicShockField;

    private object deadForACVDField;

    private object deadForGIHField;

    private object deadForOtherField;

    /// <remarks/>
    public object TreatResult
    {
        get
        {
            return this.treatResultField;
        }
        set
        {
            this.treatResultField = value;
        }
    }

    /// <remarks/>
    public object DeadTime
    {
        get
        {
            return this.deadTimeField;
        }
        set
        {
            this.deadTimeField = value;
        }
    }

    /// <remarks/>
    public object DeadForVentriclarArrhythmias
    {
        get
        {
            return this.deadForVentriclarArrhythmiasField;
        }
        set
        {
            this.deadForVentriclarArrhythmiasField = value;
        }
    }

    /// <remarks/>
    public object DeadForCardiacArrest
    {
        get
        {
            return this.deadForCardiacArrestField;
        }
        set
        {
            this.deadForCardiacArrestField = value;
        }
    }

    /// <remarks/>
    public object DeadForCardiogenicShock
    {
        get
        {
            return this.deadForCardiogenicShockField;
        }
        set
        {
            this.deadForCardiogenicShockField = value;
        }
    }

    /// <remarks/>
    public object DeadForACVD
    {
        get
        {
            return this.deadForACVDField;
        }
        set
        {
            this.deadForACVDField = value;
        }
    }

    /// <remarks/>
    public object DeadForGIH
    {
        get
        {
            return this.deadForGIHField;
        }
        set
        {
            this.deadForGIHField = value;
        }
    }

    /// <remarks/>
    public object DeadForOther
    {
        get
        {
            return this.deadForOtherField;
        }
        set
        {
            this.deadForOtherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MedicalCertificate.xsd")]
public partial class MedicalCertificateThrombolyticReason
{
    private object thrombolyticForDisagreeField;

    private object thrombolyticForEconomicReasonField;

    private object thrombolyticForDreamField;

    private object thrombolyticForTimeLimitedField;

    /// <remarks/>
    public object ThrombolyticForDisagree
    {
        get
        {
            return this.thrombolyticForDisagreeField;
        }
        set
        {
            this.thrombolyticForDisagreeField = value;
        }
    }

    /// <remarks/>
    public object ThrombolyticForEconomicReason
    {
        get
        {
            return this.thrombolyticForEconomicReasonField;
        }
        set
        {
            this.thrombolyticForEconomicReasonField = value;
        }
    }

    /// <remarks/>
    public object ThrombolyticForDream
    {
        get
        {
            return this.thrombolyticForDreamField;
        }
        set
        {
            this.thrombolyticForDreamField = value;
        }
    }

    /// <remarks/>
    public object ThrombolyticForTimeLimited
    {
        get
        {
            return this.thrombolyticForTimeLimitedField;
        }
        set
        {
            this.thrombolyticForTimeLimitedField = value;
        }
    }
}